# Generated by Django 5.1.1 on 2026-05-07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dough',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='РўРµСЃС‚Рѕ')),
            ],
            options={
                'verbose_name': 'РўРµСЃС‚Рѕ',
                'verbose_name_plural': 'РўРµСЃС‚Р°',
            },
        ),
        migrations.CreateModel(
            name='Toppings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='РќР°Р·РІР°РЅРёРµ')),
                ('slug', models.SlugField(max_length=64, unique=True, verbose_name='РЎР»Р°Рі')),
            ],
            options={
                'verbose_name': 'Р”РѕР±Р°РІРєР°',
                'verbose_name_plural': 'Р”РѕР±Р°РІРєРё',
            },
        ),
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='РќР°Р·РІР°РЅРёРµ')),
                ('description', models.TextField(verbose_name='РћРїРёСЃР°РЅРёРµ')),
                ('price', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Р¦РµРЅР°')),
                ('image', models.ImageField(blank=True, null=True, upload_to='menu/', verbose_name='Р¤РѕС‚Рѕ')),
                ('dough', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.dough', verbose_name='РўРµСЃС‚Рѕ')),
                ('toppings', models.ManyToManyField(to='main.toppings', verbose_name='РўРѕРїРїРёРЅРіРё')),
            ],
            options={
                'verbose_name': 'РџРёС†С†Р°',
                'verbose_name_plural': 'РџРёС†С†С‹',
            },
        ),
        migrations.CreateModel(
            name='Snacks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='РќР°Р·РІР°РЅРёРµ')),
                ('description', models.TextField(verbose_name='РћРїРёСЃР°РЅРёРµ')),
                ('price', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Р¦РµРЅР°')),
                ('image', models.ImageField(blank=True, null=True, upload_to='menu/', verbose_name='Р¤РѕС‚Рѕ')),
            ],
            options={
                'verbose_name': 'Р—Р°РєСѓСЃРєР°',
                'verbose_name_plural': 'Р—Р°РєСѓСЃРєРё',
            },
        ),
        migrations.CreateModel(
            name='Drinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='РќР°Р·РІР°РЅРёРµ')),
                ('description', models.TextField(verbose_name='РћРїРёСЃР°РЅРёРµ')),
                ('price', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Р¦РµРЅР°')),
                ('image', models.ImageField(blank=True, null=True, upload_to='menu/', verbose_name='Р¤РѕС‚Рѕ')),
            ],
            options={
                'verbose_name': 'РќР°РїРёС‚РѕРє',
                'verbose_name_plural': 'РќР°РїРёС‚РєРё',
            },
        ),
        migrations.CreateModel(
            name='Desserts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='РќР°Р·РІР°РЅРёРµ')),
                ('description', models.TextField(verbose_name='РћРїРёСЃР°РЅРёРµ')),
                ('price', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Р¦РµРЅР°')),
                ('image', models.ImageField(blank=True, null=True, upload_to='menu/', verbose_name='Р¤РѕС‚Рѕ')),
            ],
            options={
                'verbose_name': 'Р”РµСЃРµСЂС‚',
                'verbose_name_plural': 'Р”РµСЃРµСЂС‚С‹',
            },
        ),
    ]
