# Generated by Django 5.1.1 on 2026-05-07 12:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_order_orderitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='desserts',
            options={'verbose_name': 'Десерт', 'verbose_name_plural': 'Десерты'},
        ),
        migrations.AlterModelOptions(
            name='dough',
            options={'verbose_name': 'Тесто', 'verbose_name_plural': 'Теста'},
        ),
        migrations.AlterModelOptions(
            name='drinks',
            options={'verbose_name': 'Напиток', 'verbose_name_plural': 'Напитки'},
        ),
        migrations.AlterModelOptions(
            name='pizza',
            options={'verbose_name': 'Пицца', 'verbose_name_plural': 'Пиццы'},
        ),
        migrations.AlterModelOptions(
            name='snacks',
            options={'verbose_name': 'Закуска', 'verbose_name_plural': 'Закуски'},
        ),
        migrations.AlterModelOptions(
            name='toppings',
            options={'verbose_name': 'Добавка', 'verbose_name_plural': 'Добавки'},
        ),
        migrations.AlterField(
            model_name='desserts',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='desserts',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='menu/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='desserts',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='desserts',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='dough',
            name='title',
            field=models.CharField(max_length=30, verbose_name='Тесто'),
        ),
        migrations.AlterField(
            model_name='drinks',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='drinks',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='menu/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='drinks',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='drinks',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='dough',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.dough', verbose_name='Тесто'),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='menu/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='toppings',
            field=models.ManyToManyField(to='main.toppings', verbose_name='Топпинги'),
        ),
        migrations.AlterField(
            model_name='snacks',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='snacks',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='menu/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='snacks',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='snacks',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='toppings',
            name='slug',
            field=models.SlugField(max_length=64, unique=True, verbose_name='Слаг'),
        ),
        migrations.AlterField(
            model_name='toppings',
            name='title',
            field=models.CharField(max_length=30, verbose_name='Название'),
        ),
    ]
